[package]
name = "rainfrog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20.0"
wasm-bindgen = "0.2"
web-sys = "0.3.61"
log = "0.4"